---
kind: pipeline
name: Default

platform:
  os: linux
  arch: amd64

steps:
- name: Check code
  image: ubuntu:latest
  command:
  - echo $PATH
  - apt update
  - apt install -y curl
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
  - cargo +nightly check

- name: Check code formatting
  image: ubuntu:latest
  command:
  - apt update
  - apt install -y curl
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
  - cargo +nightly fmt -- --check

- name: Check clippy suggestions
  image: ubuntu:latest
  command:
  - apt update
  - apt install -y curl
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
  - cargo +nightly clippy

trigger:
  event:
  - push
  - pull_request

...
