version: "3"
volumes:
    node_modules:
services:
    registry:
        network_mode: host
        image: registry:2
        ports:
            - 5000:5000
        volumes:
            - ./data:/data
            - ./certs/example.org.crt:/certs/server.crt
            - ./config.yml:/etc/docker/registry/config.yml
