version: "3"

services:
  registry:
    network_mode: host
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./dev.registry.yml:/etc/docker/registry/config.yml
      - ./certs:/certs
