[package]
name = "drive-frontend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.69"
yew-router = "0.14.0"
