version: "3"
volumes:
    node_modules:
services:
    registry:
        network_mode: host
        image: registry:2
        ports:
            - 5000:5000
        volumes:
            - ./registry/data:/data
            - ./registry/certs:/certs
            - ./registry/config.yml:/etc/docker/registry/config.yml
    bytesonus_api:
        environment:
            JUNO_SOCK: /usr/juno.sock
        build:
            context: "../"
            dockerfile: "./docker/Dockerfile.dev"
        networks:
            bytesonus:
                aliases:
                    - api.bytesonus.co
                    - auth.bytesonus.co
                    - assets.bytesonus.co
            db:
        ports:
            - 5001:5001
        volumes:
            - ~/juno.sock:/usr/juno.sock
            - ..:/usr/src/app
            - node_modules:/usr/src/app/node_modules
            - ./registry/certs:/certs
            - /var/run/docker.sock:/var/run/docker.sock
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: bytesonus
            MYSQL_USER: bytesonus
            MYSQL_PASSWORD: bytesonus
            MYSQL_ROOT_PASSWORD: root
        networks:
            db:
    redis:
        image: redislabs/rejson
        networks:
            db:
networks:
    bytesonus:
    db:
