version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode
    environment:
      - PGHOST=localhost
      - PGUSER=postgres
      - PG_PASSWORD=postgres

  postgres:
    container_name: postgres
    image: postgis/postgis:13-master
    restart: unless-stopped
    network_mode: service:app
    environment:
      - POSTGRES_PASSWORD=postgres
