version: '3'

networks:
  vpc:


volumes:
  postgres-data:


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    user: vscode
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PG_PASSWORD=postgres
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh:/home/vscode/.ssh:ro
    depends_on:
      - postgres
      - redis
      - tracing
    hostname: backend
    networks:
      vpc:
        aliases:
          - backend

  postgres:
    image: postgis/postgis:13-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
      - PGDATA=/var/lib/postgresql/data
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres
    networks:
      vpc:
        aliases:
          - postgres

  redis:
    image: redis:7
    restart: unless-stopped
    expose:
      - 6379
    hostname: redis
    networks:
      vpc:
        aliases:
          - redis

  tracing:
    image: jaegertracing/all-in-one:1
    restart: unless-stopped
    expose:
      - 4317
      - 4318
      - 16686
    hostname: tracing
    networks:
      vpc:
        aliases:
          - tracing
