[build]
rustflags = ["--cfg=web_sys_unstable_apis", "-C", "link-arg=-fuse-ld=lld"]

[alias]
serve = "leptos serve"
watch = "leptos watch --hot-reload"
prepare = "sqlx prepare --workspace"
patr = "run -p cli --"
