name = "patr-ingress"
main = "src/index.ts"
compatibility_date = "2023-02-08"

kv_namespaces = [
    { binding = "ROUTING", id = "96c1b29aded04e53895eaf80f2f1d56f", preview_id = "96c1b29aded04e53895eaf80f2f1d56f"},
    { binding = "DEPLOYMENT", id = "3566504d8a144e8f8661c7e5ca9fde73", preview_id = "3566504d8a144e8f8661c7e5ca9fde73" },
    { binding = "STATIC_SITE", id = "7323c5425f354e09a11de3bc779e5eda", preview_id = "7323c5425f354e09a11de3bc779e5eda" },
]

r2_buckets = [
    { binding = "STATIC_SITE_STORAGE", bucket_name = "patr-static-site-storage", preview_bucket_name = "patr-static-site-storage" }
]

[vars]
ONPATR_DOMAIN = "onpatr.cloud"
