[package]
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
edition = "2018"
name = "macros"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
askama = "0.10.3"
handlebars = "3.5.1"
heck = "0.3.2"
proc-macro2 = "1.0.24"
quote = "1.0.8"
serde = "1.0.116"
serde_json = "1.0.58"
syn = "1.0.42"
