[package]
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
edition = "2018"
name = "api"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.10.3"
async-std = {version = "=1.6.2", features = ["attributes"]}
async-trait = "0.1.36"
bytes = "0.5.5"
clap = "2.33.1"
colored = "1.9.3"
config = "0.10.1"
eve-rs = "0.1.0"
hex = "0.4.2"
job_scheduler = {git = "https://github.com/alopatindev/job_scheduler/", branch = "fix-issue-20"}
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"
lettre = "0.10.0-alpha.1"
log = "0.4.8"
macros = {path = "../macros"}
once_cell = "1.4.1"
rand = "0.7.3"
regex = "1.3.9"
rust-argon2 = "0.8.2"
rust-s3 = "0.26.1"
semver = "0.10.0"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.57"
sqlx = {version = "0.3.5", features = ["mysql", "postgres"]}
strum = "0.19.2"
strum_macros = "0.19.2"
surf = "1.0.3"
uuid = "0.8.1"

[dependencies.log4rs]
default-features = false
features = [
  "console_appender",
  "rolling_file_appender",
  "compound_policy",
  "fixed_window_roller",
  "size_trigger",
  "background_rotation",
  "threshold_filter",
  "gzip",
]
version = "0.12.0"
