[package]
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
default-run = "api"
edition = "2018"
name = "api"
version = "0.4.4"

[features]
default = []
sample-data = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api_macros = { path = "../macros", package = "macros" }
argon2 = "0.3.1"
askama = "0.10.3"
async-trait = "0.1.36"
base32 = "0.4.0"
base64 = "0.13.0"
bytes = "1.0.1"
chrono = "0.4.19"
clap = "2.33.3"
cloudflare = "0.8.7"
colored = "2.0.0"
config_rs = { version = "0.11.0", package = "config" }
cron = "0.9.0"
eve-rs = { git = "https://github.com/vicara-hq/eve-rs", branch = "develop" }
futures = "0.3.8"
handlebars = "4.0.0"
hex = "0.4.2"
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"
lettre = { version = "=0.10.0-rc.3", features = [
  "tokio1",
  "smtp-transport",
  "tokio1-native-tls",
] }
lightsail = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.16-alpha", package = "aws-sdk-lightsail" }
log = "0.4.8"
num_cpus = "1.13.0"
once_cell = "1.4.1"
openssh = "0.8.1"
rand = "0.8.3"
redis = { version = "0.21.2", features = ["tokio-comp", "tokio-native-tls-comp"] }
regex = "1.3.9"
reqwest = { version = "0.11.3", features = ["json", "multipart"] }
rust-s3 = { version = "0.27.0", features = [
  "tokio-rustls-tls",
  "with-tokio",
] }
semver = "1.0.0"
serde = { version = "1.0.114", features = ["serde_derive"] }
serde_json = "1.0.57"
sha2 = "0.9.3"
shiplift = "0.7"
sqlx = { version = "0.5", features = [
  "postgres",
  "runtime-tokio-rustls",
  "offline",
  "ipnetwork",
  "bigdecimal",
] }
tokio = { version = "1", features = ["full"] }
trust-dns-client = "0.20"
uuid = "0.8.1"

[dependencies.log4rs]
default-features = false
features = [
  "console_appender",
  "rolling_file_appender",
  "compound_policy",
  "fixed_window_roller",
  "size_trigger",
  "background_rotation",
  "threshold_filter",
  "gzip",
]
version = "1"
