[package]
authors = ['Rakshith Ravi <rakshith.ravi@gmx.com>']
edition = '2018'
name = 'api'
version = '0.1.0'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api_macros = {path = '../macros', package = 'macros'}
askama = '0.10.3'
async-trait = '0.1.36'
bytes = '0.5.5'
chrono = '0.4.19'
clap = "2.33.3"
cloudflare = {git = 'https://github.com/rakshith-ravi/cloudflare-rs'}
colored = '1.9.3'
config_rs = {version = '0.10.1', package = 'config'}
cron = '0.6.1'
eve-rs = "0.2.0"
hex = '0.4.2'
jsonwebtoken = '7.2.0'
lazy_static = '1.4.0'
lettre = '=0.10.0-alpha.2'
log = '0.4.8'
once_cell = '1.4.1'
rand = '0.7.3'
redis = '0.17.0'
regex = '1.3.9'
rust-argon2 = '0.8.2'
rust-s3 = '0.26.1'
semver = '0.10.0'
serde = '1.0.114'
serde_derive = '1.0.114'
serde_json = '1.0.57'
sqlx = {version = '0.4.1', features = ['mysql', 'postgres', 'runtime-tokio-rustls', 'offline']}
strum = '0.19.2'
strum_macros = '0.19.2'
surf = '1.0.3'
tokio = {version = '0.2.22', features = ['full']}
trust-dns-client = '0.19.5'
uuid = '0.8.1'
futures = "0.3.8"

[dependencies.log4rs]
default-features = false
features = [
  'console_appender',
  'rolling_file_appender',
  'compound_policy',
  'fixed_window_roller',
  'size_trigger',
  'background_rotation',
  'threshold_filter',
  'gzip',
]
version = '0.12.0'
